# Generated by Django 4.0.5 on 2022-06-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='First_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('numbers_auto', models.CharField(max_length=15)),
                ('first_m', models.IntegerField()),
                ('second_m', models.IntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='grocery.product')),
            ],
        ),
    ]
