# Generated by Django 4.0.5 on 2022-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_first_stage_first_m_alter_first_stage_second_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_stage',
            name='first_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='first_stage',
            name='second_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
