# Generated by Django 4.0.5 on 2022-06-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_first_stage_first_m_alter_first_stage_second_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mass', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Склад', 'Склад'), ('Продажа', 'Продажа')], default='', max_length=10)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container', to='grocery.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container', to='grocery.warehouse')),
            ],
        ),
    ]
