# Generated by Django 4.0.5 on 2022-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_rename_mass_container_mass1_container_mass2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_stage',
            name='first_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='first_stage',
            name='second_m',
            field=models.IntegerField(default=0),
        ),
    ]
