# Generated by Django 4.0.5 on 2022-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_first_stage_first_m_alter_first_stage_second_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_stage',
            name='box_mass',
            field=models.IntegerField(default=0),
        ),
    ]
