# Generated by Django 4.0.5 on 2022-06-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_first_stage_box_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_stage',
            name='box_mass',
        ),
        migrations.AddField(
            model_name='container',
            name='box_mass',
            field=models.IntegerField(default=0),
        ),
    ]
