# Generated by Django 4.0.5 on 2022-06-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_remove_first_stage_box_mass_container_box_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='mass_product',
        ),
    ]
