# Generated by Django 4.0.5 on 2022-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_remove_container_mass_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='box_mass',
            new_name='box_mass1',
        ),
        migrations.AddField(
            model_name='container',
            name='box_mass2',
            field=models.IntegerField(default=0),
        ),
    ]
