# Generated by Django 4.0.5 on 2022-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_rename_box_mass_container_box_mass1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='box_mass1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='box_mass2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='mass1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='mass2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='first_stage',
            name='first_m',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='first_stage',
            name='second_m',
            field=models.FloatField(default=0),
        ),
    ]
