# Generated by Django 4.0.5 on 2022-07-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_alter_container_box_mass1_alter_container_box_mass2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Продажа', 'Продажа'), ('Отходы', 'Отходы'), ('Отгружено', 'Отгружено')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='container',
            name='stores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='grocery.store'),
            preserve_default=False,
        ),
    ]
