# Generated by Django 4.0.5 on 2022-07-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_alter_container_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='grocery.store'),
        ),
    ]
