# Generated by Django 4.0.5 on 2022-08-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0015_alter_container_stores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Контейнер', 'verbose_name_plural': 'Контейнер'},
        ),
        migrations.AlterModelOptions(
            name='first_stage',
            options={'verbose_name': 'Приход', 'verbose_name_plural': 'Приход'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
    ]
