# Generated by Django 4.0.5 on 2022-08-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_alter_container_options_alter_first_stage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Продажа', 'Продажа'), ('Отходы', 'Отходы'), ('Отгружено', 'Отгружено')], default='', max_length=10, null=True),
        ),
    ]
