# Generated by Django 4.0.5 on 2022-08-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0017_container_status1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass1', models.FloatField(default=0)),
                ('mass2', models.FloatField(default=0)),
                ('packaging', models.CharField(choices=[('Мешок', 'Мешок'), ('Сетка', 'Сетка')], default='', max_length=10)),
                ('status', models.CharField(choices=[('Склад', 'Склад'), ('Продажа', 'Продажа')], default='', max_length=10)),
                ('status1', models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Продажа', 'Продажа')], default='', max_length=10, null=True)),
                ('number_pr', models.IntegerField(default=0)),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tray', to='grocery.store')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tray', to='grocery.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tray', to='grocery.warehouse')),
            ],
        ),
    ]
