# Generated by Django 4.0.5 on 2022-08-20 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_tray'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tray',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы')], default='', max_length=10, null=True),
        ),
    ]
