# Generated by Django 4.0.5 on 2022-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0020_alter_tray_options_alter_container_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы'), ('', '')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы'), ('', '')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Продажа', 'Продажа'), ('', '')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tray',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Продажа', 'Продажа'), ('', '')], default='', max_length=10, null=True),
        ),
    ]
