# Generated by Django 4.0.5 on 2022-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0021_alter_container_status_alter_container_status1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы'), (' ', ' ')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Сортировка', 'Сортировка'), ('Отходы', 'Отходы'), (' ', ' ')], default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='status',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Продажа', 'Продажа'), (' ', ' ')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='tray',
            name='status1',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Продажа', 'Продажа'), (' ', ' ')], default=' ', max_length=10, null=True),
        ),
    ]
