# Generated by Django 4.0.5 on 2022-08-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0022_alter_container_status_alter_container_status1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tray',
            old_name='packaging',
            new_name='packing',
        ),
    ]
